### ISSUE TITLE
Example code won't build with log = "0.4.14"

### ISSUE THREAD

**Issue by lichr** [http-rs/tide#787]
just tried to run the "get started" example and it failed to build, with error like

```
error[E0277]: the trait bound `std::string::String: ToValue` is not satisfied
   --> /home/cli/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.15.0/src/listener/failover_listener.rs:112:21
    |
112 | /                     crate::log::info!("unable to bind", {
113 | |                         listener: listener.to_string(),
114 | |                         error: e.to_string()
115 | |                     });
    | |_______________________^ the trait `ToValue` is not implemented for `std::string::String`
    |
    = note: required for the cast to the object type `dyn ToValue`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
Look like the latest log 0.4.14 which was installed by default causes the problem, have to explicitly specify using the previous version so that it can build
```toml
# this works
log = "=0.4.13"
```

**Comment by etherealvisage** [comment]
Also just ran into this, looks like the problem is that log 0.4.14 moved the implementation of `ToValue` for `String` into the [`kv_unstable_std` feature](https://docs.rs/log/0.4.14/src/log/kv/value.rs.html#433-437) instead of the [`std` feature](https://docs.rs/log/0.4.13/src/log/kv/value/impls.rs.html#105-109). I think this counts as an upstream bug?

**Comment by pepoviola** [comment]
I also run into this issue in a ci build today. @yoshuawuyts can we lock the version to workaround on the upstream issue?

Thx!

**Comment by yoshuawuyts** [comment]
Sounds good. If you can file a PR I can merge + issue a patch release tomorrow morning (a few hours from now)

probably cc/ @kodraus as well

**Comment by pepoviola** [comment]
Hi @yoshuawuyts, thanks for the reply. This [pr](https://github.com/http-rs/tide/pull/776#issuecomment-768628833) fix this issue. I will resolve the conflicts and ping you there.
Thx!
